---
- hosts:  all
  become: true
  tasks: 

  - name: update patch
    zypper:
     update_cache: yes

  - name: inatall apache2 package
    zypper:
     name: apache2
    when: ansible_distribution == "Centos" and ansible_version == "8"
